USE DATABASE RETAIL_DEV;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS FF_CSV_STANDARD
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;

CREATE FILE FORMAT IF NOT EXISTS FF_JSON_STANDARD
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE;